{% set name = "lazyimread" %}
{% set version = "0.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lyehe/lazyimread/archive/v{{ version }}.tar.gz
  sha256: 05cdc560013033406e39d321abc859b20bb23d8fc15a9e84808fe966f204542e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.20
    - opencv >=4.0
    - tifffile >=2021.0
    - h5py >=3.0
    - zarr >=2.10
    - xmltodict >=0.12
    - pyyaml >=5.0

test:
  imports:
    - lazyimread
  commands:
    - pip check
    - python -c "import lazyimread; print(lazyimread.__version__)"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lyehe/lazyimread
  summary: A lazy image reading library for various file formats
  description: |
    Lazyimread is a Python library that simplifies working with large, 
    multi-dimensional image datasets. It can handle importing of various 
    image file formats such as TIFF, HDF5, Zarr, image sequences, and 
    video files without writing boilerplate code for each format.
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lyehe
